fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "lucadowdenanthony@gmail.com"
    sender_name: "Luca Dowden"

  profile:
    form:
      type: App\Form\ProfileEditType